# Generated by Django 5.1.3 on 2024-11-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measuring_point", models.CharField(max_length=256)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=256)),
            ],
        ),
    ]
