# Generated by Django 5.1.3 on 2024-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0002_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='picture',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
