# Generated by Django 5.1.3 on 2024-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floodproject", "0002_waterlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
