# Generated by Django 4.2.1 on 2024-12-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
