# Generated by Django 5.1.3 on 2024-11-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floodproject", "0003_report_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="x_coordinate",
        ),
        migrations.RemoveField(
            model_name="report",
            name="y_coordinate",
        ),
        migrations.AddField(
            model_name="report",
            name="lat",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="lon",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
