# Generated by Django 5.1.3 on 2024-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0003_report_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='picture_description',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
