# Generated by Django 5.1.3 on 2024-11-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floodproject", "0004_remove_report_x_coordinate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
