# Generated by Django 5.1.3 on 2024-12-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0004_report_picture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='picture_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
