# Generated by Django 4.2.1 on 2024-12-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0003_remove_customuser_is_verified'),
        ('floodproject', '0006_alter_report_picture_description'),
    ]

    operations = [
    ]
