# Generated by Django 4.2.1 on 2024-12-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0007_merge_20241208_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
