# Generated by Django 5.1.3 on 2024-12-25 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0010_remove_vote_downvote_remove_vote_upvote_vote_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floodproject.report')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
