# Generated by Django 5.1.3 on 2024-12-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
