# Generated by Django 5.1.3 on 2024-12-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0012_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
