# Generated by Django 5.1.3 on 2024-12-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0014_alter_comment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterLevel',
        ),
    ]
