# Generated by Django 5.1.3 on 2024-12-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0016_subscriber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('report_id', 'user_id')},
        ),
    ]
