# Generated by Django 5.1.3 on 2024-12-29 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0017_alter_subscriber_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subscription',
        ),
    ]
