# Generated by Django 5.1.3 on 2025-01-06 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "floodproject",
            "0019_task_status_alter_report_user_id_alter_task_agentid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="agentID",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("To-Do", "To-Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To-Do",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="agentID",
            field=models.ManyToManyField(
                related_name="agents_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
