# Generated by Django 5.1.3 on 2025-01-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floodproject", "0020_remove_task_agentid_alter_task_status_task_agentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reportID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="floodproject.report",
            ),
            preserve_default=False,
        ),
    ]
