# Generated by Django 5.1.3 on 2025-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floodproject", "0021_task_reportid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("agent", "Agent"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
