# Generated by Django 5.1.3 on 2025-01-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0022_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='agentID',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='managerID',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reportID',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('report', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('report', 'user')},
        ),
    ]
