# Generated by Django 5.1.3 on 2025-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0023_rename_report_id_comment_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
