# Generated by Django 5.1.3 on 2025-01-14 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodproject', '0026_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedDate',
            new_name='assigned_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
